albums['Carroll Gardens'] = {
	'artist': 'Corduroy',
	'date': 'March 4th, 2020',
	'liner notes': "Recorded live inside of a canel\u00E9. Carroll gardens, a collection of songs that I've manifested sometime during the last 2 years. As such, my level of experience and even the DAWs I use vary throughout the album, so don't expect anything too cohesive. Some of the songs were made in GarageBand, the majority were made in Logic Pro X. Occasionally I've used a MIDI keyboard, but other than that, no physical gear. Oh wait, one of the songs samples this huge dusty piano at Hunter College that I was playing in my break before discrete math. Also, in the song with marc we used an electric guitar, and LIAR has my old acoustic guitar with a hole in it. Other than that, it's all virtual instruments, VSTs, and samples. I would like to give a shout out to compressors, for making everything warm and fuzzy. That is all, enjoy, please.",
};

albums['Carroll Gardens']['tracklist'] =
[
	{ "name": "new york antipasto",
	  "time": "00:00 - 01:48",
	},
	{ "name": "sunday",
	  "time": "01:49 - 03:50",
	},
	{ "name": "fizzzzzi snowflake",
	  "time": "03:51 - 04:35",
	},
	{ "name": "earrings",
	  "time": "04:36 - 06:25",
	},
	{ "name": "purple heater",
	  "time": "06:26 - 07:08",
	},
	{ "name": "icy cough",
	  "time": "07:09 - 08:39",
	},
	{ "name": "torreador interlude",
	  "time": "08:40 - 08:51",
	},
	{ "name": "let us fall",
	  "time": "08:52 - 11:10",
	},
	{ "name": "mic check 2",
	  "time": "11:11 - 13:34",
	},
	{ "name": "marc (feat. captain marc of her majesty's cockles and mussels)",
	  "time": "13:35 - 14:12",
	},
	{ "name": "big lenny",
	  "time": "14:13 - 16:09",
	},
	{ "name": "mozart(((",
	  "time": "16:10 - 17:13",
	},
	{ "name": "alex (feat. brother quaker aleksandr)",
	  "time": "17:14 - 17:55",
	},
	{ "name": "erth",
	  "time": "17:56 - 18:58",
	},
	{ "name": "north",
	  "time": "18:59 - 20:04",
	},
	{ "name": "grandfather",
	  "time": "20:05 - 21:21",
	},
	{ "name": "LIAR",
	  "time": "21:22 - 22:06",
	},
	{ "name": "sirens on my stoop",
	  "time": "22:07 - 23:54",
	},
	{ "name": "andata",
	  "time": "23:55 - 24:44",
	},
	{ "name": "clark2",
	  "time": "24:45 - 26:14",
	},
	{ "name": "caesarea",
	  "time": "26:15 - 26:37",
	},
	{ "name": "n\u00F6cht",
	  "time": "26:38 - 27:22",
	},
	{ "name": "cotton blues",
	  "time": "27:23 - 28:10",
	},
	{ "name": "the sounds in my cochlea on february 14th",
	  "time": "28:11 - 28:59",
	},
	{ "name": "evenings in rome",
	  "time": "29:00 - 29:57",
	},
];
